update mise location

diff --git a/.chezmoiscripts/run_onchange_after_install_packages.sh.tmpl b/.chezmoiscripts/run_onchange_after_install_packages.sh.tmpl
--- a/.chezmoiscripts/run_onchange_after_install_packages.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_after_install_packages.sh.tmpl
@@ -1,3 +1,15 @@
 #!/bin/bash
 # packages hash: {{ include "dot_config/mise/config.toml" | sha256sum }}
-$HOME/.local/bin/mise trust $HOME/.config/mise/config.toml && $HOME/.local/bin/mise install
+
+mise_bin="$(command -v mise)"
+
+if [ -x "$mise_bin" ]; then
+  # Trust the directory where .mise.toml is located
+  cd "$HOME/.config/mise" || exit 1
+  "$mise_bin" trust . && \
+  "$mise_bin" install
+else
+  echo "❌ mise not found in PATH. Please ensure it is installed." >&2
+  exit 1
+fi
+
